version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass_root
      MYSQL_DATABASE: your_db
      MYSQL_ROOT_USER: root_user
      MYSQL_PASSWORD: user_pass
    ports:
      - '3306:3306'